import { fetchMe } from '@/lib/utils/supabase/server'
import type { Metadata } from 'next'
import { redirect } from 'next/navigation'
import { PropsWithChildren } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function AuthLayout({ children }: PropsWithChildren) {
  // todo: remove getUser from layout (seems like it's not recommended)
  const { error } = await fetchMe()

  if (!error) {
    redirect('/dashboard')
  }

  return (
    <main>
      <section className='flex min-h-screen w-full'>
        <div className='hidden flex-1 items-end justify-center rounded-r-2xl bg-auth-banner bg-cover bg-bottom bg-no-repeat text-xl italic lg:flex'>
          <h1 className=' items-center pb-4'>
            The place to dump your important files
          </h1>
        </div>
        <div className='flex flex-1 items-center justify-center'>
          {children}
        </div>
      </section>
    </main>
  )
}
