import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { dir } from 'i18next'

import { Toaster } from '@/ui'
import { ThemeProvider } from '@/providers'

import '@/styles/globals.css'

import { i18n, type Locale } from '@/lib/i18n'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] })

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: { lang: Locale }
}>) {
  return (
    <html lang={params.lang} dir={dir(params.lang)}>
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  )
}
